export const data = {
  "House 1": "With the Sun in Aries in the First House, you possess a powerful, dynamic personality. You're a natural leader with boundless energy and enthusiasm. Your self-expression is direct and forceful, and you're not afraid to take initiative. This placement enhances your pioneering spirit and ability to start new projects.",
  "House 2": "The Sun in Aries in your Second House brings a dynamic approach to material resources. You're enterprising and confident in financial matters, though sometimes impulsive with spending. You value independence and may prefer to earn your own way rather than rely on others.",
  "House 3": "This placement gives you a quick, active mind and direct communication style. You're enthusiastic in learning and sharing ideas, often being the first to speak up. Your thoughts and speech are energetic and inspiring to others.",
  "House 4": "Your home life is energetic and dynamic. You may be the leader of your household, taking initiative in family matters. There's a strong need to establish your own living space and make independent decisions about your domestic life.",
  "House 5": "With the Sun in Aries in the Fifth House, you are creative and enthusiastic in your self-expression. You enjoy taking risks in love and creativity, often being the life of the party.",
  "House 6": "In the Sixth House, the Sun in Aries brings a dynamic approach to work and health. You're industrious and prefer to lead in your professional environment, taking the initiative in projects.",
  "House 7": "The Sun in Aries in the Seventh House makes you assertive in partnerships. You seek dynamic and independent partners, often taking the lead in relationships.",
  "House 8": "In the Eighth House, the Sun in Aries gives you a fearless approach to transformation and shared resources. You are bold in dealing with change and may have a strong interest in the mysteries of life.",
  "House 9": "With the Sun in Aries in the Ninth House, you are adventurous in your pursuit of knowledge. You are drawn to new philosophies and cultures, often seeking to expand your horizons through travel and study.",
  "House 10": "The Sun in Aries in the Tenth House enhances your leadership qualities in your career. You're ambitious and driven, often seeking positions of authority and recognition.",
  "House 11": "In the Eleventh House, the Sun in Aries makes you a dynamic and inspirational presence in groups and friendships. You are often seen as a leader among peers, with a strong desire to make a difference.",
  "House 12": "The Sun in Aries in the Twelfth House gives you a strong inner drive and spiritual energy. You may work behind the scenes to achieve your goals, with a focus on personal growth and self-discovery."
};